function lines = lines_selection(interactive, l_faces, l_floor, im)
    if ~interactive
        l_faces = line2homogeneous(l_faces);
        l_floor = line2homogeneous(l_floor);
        % ============================ HARCODED LINES =====================
        % left horizontal face long lines
        lhl = [l_faces(10, :); l_faces(23, :); l_faces(4, :); ...
                l_faces(1, :); l_faces(8, :)];
        % left horizontal face short lines
        lhs = [l_faces(81, :); l_faces(34, :)];
        % right horizontal face long lines
        rhl = [l_faces(16, :); l_faces(12, :); l_faces(77, :); ...
            l_faces(72, :)];
        % right horizontal_faces face short l_facesines
        rhs = [l_faces(70, :); l_faces(67, :)];
        % floor lines (only one direction)
        fl1 = [l_floor(13, :); l_floor(2, :); l_floor(22, :)];
        fl2 = [l_floor(19, :); l_floor(24, :)];
        % vertical faces vertical lines
        vl = [l_faces(26, :); l_faces(15, :); l_faces(11, :); ...
            l_faces(21, :); l_faces(7, :)];
        left_face_edges = struct(   'right',    l_faces(8, :),   ... 
                                    'left',     l_faces(23, :),   ...
                                    'top',      l_faces(81, :),  ...
                                    'bottom',   l_faces(34, :));
        right_face_edges = struct(  'right',    l_faces(72, :), ...
                                    'top',      l_faces(70, :), ...
                                    'left',     l_faces(60, :),   ...
                                    'bottom',   l_faces(67, :));
        % =================================================================
    else
        lhl = select_lines_from_click(l_faces, im, "select lines " + ...
            "parallel to the long edges of the left horizontal face " + ...
            "(also the edges can be seelcted)");
        lhl = line2homogeneous(lhl);
        lhs = select_lines_from_click(l_faces, im, "select lines " + ...
            "parallel to the short edges of the left horizontal face " + ...
            "(also the edges can be seelcted)");
        lhs = line2homogeneous(lhs);
        rhl = select_lines_from_click(l_faces, im, "select lines " + ...
            "parallel to the long edges of the right horizontal face " + ...
            "(also the edges can be seelcted)");
        rhl = line2homogeneous(rhl);
        rhs = select_lines_from_click(l_faces, im, "select lines " + ...
            "parallel to the short edges of the right horizontalface " + ...
            "(also the edges can be seelcted)");
        rhs = line2homogeneous(rhs);
        fl1 = select_lines_from_click(l_floor, im, "select parallel " + ...
            "lines on the floor");
        fl1 = line2homogeneous(fl1);
        fl2 = select_lines_from_click(l_floor, im, "select parallel " + ...
            "lines on the floor, perpendicular to the one chosen before");
        fl2 = line2homogeneous(fl2);
        vl = select_lines_from_click(l_faces, im, "select vertical " + ...
            "lines");
        vl = line2homogeneous(vl);
        l_edges = select_lines_from_click(l_faces, im, "select the " + ...
            "edges of the left horizontal face in the following " + ...
            "order: left, top, right, bottom.");
        left_face_edges = struct(   'left', ...
                                    line2homogeneous(l_edges(1)), ... 
                                    'top', ...
                                    line2homogeneous(l_edges(2)), ... 
                                    'right', ...
                                    line2homogeneous(l_edges(3)), ... 
                                    'bottom', ...
                                    line2homogeneous(l_edges(4))); 
        r_edges = select_lines_from_click(l_faces, im, "select the " + ...
            "edges of the right horizontal face in the following " + ...
            "order: left, top, right, bottom.");
        right_face_edges = struct ( 'left', ...
                                    line2homogeneous(r_edges(1)), ... 
                                    'top', ...
                                    line2homogeneous(r_edges(2)), ... 
                                    'right', ...
                                    line2homogeneous(r_edges(3)), ... 
                                    'bottom', ...
                                    line2homogeneous(r_edges(4)));
        
    end
    lines = struct( 'lhl', lhl, 'lhs', lhs, 'rhl', rhl, 'rhs', rhs, ...
                    'fl1', fl1, 'fl2', fl2, 'vl', vl, 'left_edges', left_face_edges, ...
                    'right_edges', right_face_edges);
end

    
    